version: "3.8"

services:
  # --- Base de Dados (MySQL) ---
  db:
    platform: linux/x86_64
    image: mysql:8.1
    container_name: api-diogogoncalo-projeto-final
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - internal-network

  # --- Interface da Base de Dados (PhpMyAdmin) ---
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2
    container_name: phpmyadmin5_2_tpsi0525
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - internal-network

  # --- CACHE (REDIS) - NOVO ---
  cache-redis:
    image: redis:latest
    container_name: redis-projeto-final
    restart: unless-stopped
    ports:
      # Mapeia a porta 6379 do contentor para o seu PC
      # Isto permite que a API .NET se ligue via localhost:6379 quando corre o F5
      - "6379:6379"
    volumes:
      # Opcional: cria um volume para n√£o perder o cache se reiniciar o contentor
      - redis_data:/data
    networks:
      - internal-network

networks:
  internal-network:

volumes:
  db_data:
  redis_data: # Novo volume registado