version: "3.8"

services:
  # --- Base de Dados (MySQL) ---
  db:
    platform: linux/x86_64
    image: mysql:8.1
    container_name: api-diogogoncalo-projeto-final
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - internal-network

  # --- Interface da Base de Dados (PhpMyAdmin) ---
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2
    container_name: phpmyadmin5_2_tpsi0525
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - internal-network

  # --- Cache (Redis) ---
  cache-redis:
    image: redis:latest
    container_name: redis-projeto-final
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internal-network

  # --- IMPOSTER (WireMock) - O Fornecedor Falso ---
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-fornecedor
    ports:
      # Mapeia a porta 9090 do seu PC para a 8080 do WireMock
      - "9090:8080" 
    volumes:
      # Liga a pasta que cri√°mos ao contentor, para ele ler o JSON
      - ./wiremock:/home/wiremock
    networks:
      - internal-network

networks:
  internal-network:

volumes:
  db_data:
  redis_data: